FROM rust:alpine AS builder

RUN apk add git python3 musl-dev pkgconfig openssl-dev make

WORKDIR /opt/synapse-compressor/

RUN git clone --depth=1 https://github.com/matrix-org/rust-synapse-compress-state.git .

COPY . .

RUN \
    --mount=type=cache,target=/usr/local/cargo/registry \
    RUSTFLAGS="-C target-feature=-crt-static" cargo install --path .

WORKDIR /opt/synapse-compressor/synapse_auto_compressor/

RUN \
    --mount=type=cache,target=/usr/local/cargo/registry \
    RUSTFLAGS="-C target-feature=-crt-static" cargo install --path .

FROM alpine

RUN apk add --no-cache libgcc

COPY --from=builder /opt/synapse-compressor/target/release/synapse_compress_state /usr/local/bin/synapse_compress_state
COPY --from=builder /opt/synapse-compressor/target/release/synapse_auto_compressor /usr/local/bin/synapse_auto_compressor
