name: Setup Python-Poetry and cache
description: Setup Python and Poetry, from cache if possible. Modified from Matrixdotorg/synapse, who got it from snok/install-poetry.
on:
  workflow_call:
    inputs:
      python-version:
        default: '3.10'
        type: string
        required: false
      poetry-version:
        default: '1.2.0'
        type: string
        required: false
      extras:
        default: "all"
        type: string
        required: false
      latest-deps:
        default: False
        type: boolean
        required: False

runs:
  using: composite

  steps:
    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '${{ inputs.python-version }}'

    - name: Locate user site
      id: site-user-base
      run: echo "::set-output name=dir::$(python -m site --user-base)"
      shell: bash

    - name: Restore/cache poetry installation
      id: poetry-install-cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.site-user-base.outputs.dir }}
        key: poetry-install-cache-${{ steps.setup-python.outputs.python-version }}-${{ inputs.poetry-version }}

    - name: Install poetry from scratch
      if: "${{ steps.poetry-install-cache.outputs.cache-hit != 'true' }}"
      run: python -m pip install --user poetry==${{ inputs.poetry-version }}
      shell: bash

    # Poetry manages a virtualenv for us. We're going to cache that too.
    # Again, we're following snok/install-poetry's README.
    - name: Locate poetry venv
      id: poetry-venvs
      run: echo "::set-output name=dir::$(python -m poetry config virtualenvs.path)"
      shell: bash

    - name: Restore/cache poetry venv
      id: poetry-venv-cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.poetry-venvs.outputs.dir }}
        key: poetry-venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-${{ inputs.extras }}

    - name: Update dependencies
      if: {{ inputs.latest-deps == True }}
      run: poetry update
